telegram:
  enable: false
  token: "PUT_YOUR_BOT_TOKEN_HERE"
  user-id: 123456789

mongo:
  enable: false
  uri: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.15"
  database-names:
    - "MRDatabase"
  threads: 5
  path: "backup-%name%.gz"
  interval: 1440 #minute

mysql:
  enable: false
  host: "localhost"
  port: 3306
  database-names:
    - "MRDatabase"
  username: "root"
  password: ""
  threads: 5
  path: "backup-%name%.sql"
  interval: 1440 #minute

sqlite:
  enable: false
  from-paths:
    - "/etc/lib/sqlite.db"
  path: "/root/backups"
  interval: 1440 #minute

socks5:
  enable: false
  host: "127.0.0.1"
  port: 10808
  username: ""
  password: ""